1621768920115	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1621769505852	Sync.RemoteTabs	INFO	Generating tab list with filter
1621769505854	Sync.RemoteTabs	DEBUG	Processing client: {"id":"90a4b2a8a0f259272fa758f60bf4370a","type":"client","name":"Firefox на Meizu M3s","clientType":"phone","lastModified":1621757359150,"tabs":[]}
1621769505855	Sync.RemoteTabs	INFO	Final tab list has 1 clients with 3 tabs.
1621769520116	Sync.Service	DEBUG	User-Agent: Waterfox/78.10.0 (Linux x86_64) FxSync/1.80.0.20210415101645.desktop
1621769520116	Sync.Service	INFO	Starting sync at 2021-05-23 14:32:00 in browser session 0uNcR5OYrfyu
1621769520117	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1621769520122	Sync.Status	INFO	Resetting Status.
1621769520122	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1621769520126	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1621769520127	FirefoxAccounts	DEBUG	getOAuthToken enter
1621769520136	FirefoxAccounts	TRACE	getCachedToken returning cached token
1621769520136	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1621769520137	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1621769520314	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/155119483/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a2ffe (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1621769520315	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a2ffe (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1621769520316	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1621769520332	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a2ffe (<unknown>)"  location: "<unknown>"  data: no] No traceback available
